# Generated by Django 2.2.2 on 2019-07-08 16:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='CompareResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'compare_results',
            },
        ),
    ]
