# Generated by Django 2.2.2 on 2019-07-09 12:33

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('falcon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareresults',
            name='first_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='compareresults',
            name='second_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='compareresults',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
