# Generated by Django 2.2.2 on 2019-07-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0004_auto_20190717_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
