# Generated by Django 2.2.2 on 2019-09-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0005_bookings_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildsessions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memorymetricsraw',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memorymetricsstandart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='monkeycrashes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='powermetricsraw',
            options={},
        ),
        migrations.AlterModelOptions(
            name='powermetricsstandart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='releasefeatures',
            options={},
        ),
        migrations.AlterModelOptions(
            name='releases',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testresults',
            options={},
        ),
    ]
