# Generated by Django 2.2.2 on 2019-09-23 16:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0006_auto_20190923_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsessions',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.Devices'),
        ),
        migrations.AddField(
            model_name='memorymetricsraw',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon.TestResults'),
        ),
        migrations.AddField(
            model_name='memorymetricsstandart',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.Devices'),
        ),
        migrations.AddField(
            model_name='memorymetricsstandart',
            name='test_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.TestItems'),
        ),
        migrations.AddField(
            model_name='monkeycrashes',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon.BuildSessions'),
        ),
        migrations.AddField(
            model_name='powermetricsraw',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon.TestResults'),
        ),
        migrations.AddField(
            model_name='powermetricsstandart',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.Devices'),
        ),
        migrations.AddField(
            model_name='powermetricsstandart',
            name='test_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.TestItems'),
        ),
        migrations.AddField(
            model_name='releasefeatures',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon.Releases'),
        ),
        migrations.AddField(
            model_name='testresults',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon.BuildSessions'),
        ),
        migrations.AddField(
            model_name='testresults',
            name='test_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.TestItems'),
        ),
    ]
