# Generated by Django 2.2.2 on 2019-10-24 13:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0007_auto_20190923_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsStandart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.Devices')),
            ],
            options={
                'db_table': 'metrics_standart',
            },
        ),
        migrations.CreateModel(
            name='TestMarkers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marker', models.CharField(max_length=250)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'pytest_markers',
            },
        ),
        migrations.RemoveField(
            model_name='powermetricsstandart',
            name='device',
        ),
        migrations.RemoveField(
            model_name='powermetricsstandart',
            name='test_item',
        ),
        migrations.AddField(
            model_name='buildsessions',
            name='test_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compareresults',
            name='diff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testitems',
            name='marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='testresults',
            name='is_standart',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='MemoryMetricsStandart',
        ),
        migrations.DeleteModel(
            name='PowerMetricsStandart',
        ),
        migrations.AddField(
            model_name='metricsstandart',
            name='test_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.TestItems'),
        ),
        migrations.AddField(
            model_name='metricsstandart',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon.TestResults'),
        ),
    ]
