# Generated by Django 2.2.2 on 2019-10-31 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0008_auto_20191024_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorReleases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'major_releases',
            },
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_full', models.CharField(max_length=20)),
                ('major_release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon.MajorReleases')),
            ],
            options={
                'db_table': 'versions',
            },
        ),
        migrations.DeleteModel(
            name='ReleaseFeatures',
        ),
        migrations.DeleteModel(
            name='Releases',
        ),
        migrations.AddField(
            model_name='buildsessions',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.Versions'),
        ),
    ]
