# Generated by Django 2.2.2 on 2019-11-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0009_auto_20191031_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsstandart',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.MajorReleases'),
        ),
    ]
