# Generated by Django 2.2.2 on 2020-02-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0010_metricsstandart_release'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monkeycrashes',
            old_name='crash_text',
            new_name='full_crash_text',
        ),
        migrations.CreateModel(
            name='UniqueCrash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crash_text', models.CharField(blank=True, max_length=100000, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('release', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.Devices')),
            ],
            options={
                'db_table': 'unique_monkey_crashes',
            },
        ),
        migrations.AddField(
            model_name='monkeycrashes',
            name='unique_crash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.UniqueCrash'),
        ),
    ]
