# Generated by Django 2.2.10 on 2020-07-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0011_auto_20200218_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.CharField(max_length=5000)),
                ('file', models.ImageField(blank=True, upload_to='screencaps')),
                ('timestamp', models.DateTimeField()),
                ('is_fail', models.BooleanField(default=False)),
                ('test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon.TestResults')),
            ],
        ),
    ]
