# Generated by Django 2.2.10 on 2020-07-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0012_testresultlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultlog',
            name='before',
            field=models.BooleanField(default=True),
        ),
    ]
